extraction:
  cpp:
    after_prepare: 
      - python report.py 40
  cobol:
    after_prepare: 
      - python report.py 40
  csharp:
    after_prepare: 
      - python report.py 40
  java:
    after_prepare: 
      - python report.py 40
  javascript:
    after_prepare: 
      - python report.py 40
  python:
    after_prepare: 
      - python report.py 40
